### ISSUE TITLE
Kubernetes Configmap & Secret

### ISSUE THREAD

**Issue by alazyer** [alazyer/mdblog#14]
- https://kubernetes.io/docs/concepts/configuration/secret/
- https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
- https://kubernetes.io/docs/tutorials/configuration/configure-redis-using-configmap/

**Comment by comradelemoncake** [comment]
Hey @alazyer I can help with this!

**Comment by alazyer** [comment]
@jdbohrman Hey, really appreciate your help.
However, the issues in this repo is like a bookmark with label enabled for me.
Thx again.
